# Generated by Django 3.1.3 on 2020-11-24 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('forma_pago', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=20)),
                ('id_detalle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pedido.detalle')),
            ],
        ),
        migrations.AddField(
            model_name='detalle',
            name='id_producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pedido.producto'),
        ),
    ]
