# Generated by Django 3.1.3 on 2020-12-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'pacientes'},
        ),
        migrations.AlterField(
            model_name='historial',
            name='pacient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente'),
        ),
    ]
